default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: utilities_development
  username: slavam
  password: utility-pw
test:
  <<: *default
  database: utilities_test
production:
  <<: *default
  database: utilities_production

